### PR TITLE
fix ovsdb:api:set_controller bug

### PR DESCRIPTION
**Pull request by qin-nz**
Line 373:             _uuid = controller_info.get('uuid', uuid.uuid4())
AttributeError: 'NoneType' object has no attribute 'get'

### CODE REVIEW

**Comment by iwaseyusuke** [comment]
Hi @qin-nz  

Thank you for posting your PR!
It looks good to me!

But, Ryu development team does not use Pull Request on GitHub.
We are using `"git format-patch"` style patch to discuss on [ryu-devel mailing list](https://lists.sourceforge.net/lists/listinfo/ryu-devel)
Would you mind sending your patch to this mailing list?

**Comment by qin-nz** [comment]
@iwaseyusuke 
Hi, I am new to format-patch.
I subscribe the mailing list first and then send the patch email to the list.
But I didn't received the patch email from the list. 
Is this be expected?

**Comment by iwaseyusuke** [comment]
Hi @qin-nz 

Yes, it is the expected behavior.
Ryu-devel mailing list seems not to forward to the sender address, and if you need to forward to your self, please add CC or BCC to your address.

FYI, you can confirm your mail was sent as expected or not on [this mail archive](https://sourceforge.net/p/ryu/mailman/ryu-devel/) (It might take some time to be reflected).

**Comment by qin-nz** [comment]
https://sourceforge.net/p/ryu/mailman/message/35841709/

**Pull request closed without merging**
